### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by djengle91** [djengle91/movies-ive-seen#1]
- [x] Create react app
- [x] Setup firebase
- [x] Connect react to firebase
- [x] Setup initial data and calls
- [x] Setup authentication
